### ISSUE TITLE
Narrative Pacing

### ISSUE THREAD

**Issue by Xahell** [GDL-Collaborators/indigo#9]
### What's this about?

For a time we will be designing a bunch of puzzles that will be put one after the other in the build.

This issue is trying to incorporate the first ideas about a game narrative, and is mostly about how to introduce it in the game loop.

### Narrative loop

The tower contains two types of rooms:

- Puzzles, which provide a challenge to the player
- Narrative rooms, which are a symbolic corridor giving us an opportunity to advance the narrative with the sister or a special NPC.

The game starts with a narrative room, where the sister can provide the player with a goal (getting on top of the tower to get their dearest wish).

The game provides 5 puzzles. After 5 puzzles, the player goes into a narrative room. Afterward, the player goes for another round of 5 puzzles, and so on.

### NPC

The game story is driven by the NPC. The PC is mute and will always listen to others.

Thee kinds of NPC can be found:

- The puzzle related NPC. They can be signs or characters, and usually deliver a cryptic message about the puzzle. 
- The player main companions, probably his sister. This NPC can always be found nearby, either idling somewhere in the room or following the player. What about the dog though?
- Recurrent story related NPCs (plural). Can be delivered as a recurrent puzzle-NPC, or as a NPC speaking during a narrative room.

During a puzzle, the sister can provide a hint when spoken to.

### Purpose

The narrative acts as a hook, and the puzzles as the main game activity. The player solves the puzzles to reach the next narrative part.

**Comment by collectivenectar** [comment]
I was going to mention, by the way, as far as plot goes, I was thinking about the whole 'leaving the dog behind' device I saw mentioned in discord as maybe being part of one of the final puzzles. I actually like it, it's very 'approach to the innermost cave' - a phrase referring to movie plot structure where the hero has to go alone to confront their ultimate fears and doubts about their journey. see http://www.movieoutline.com/articles/the-hero-journey-mythic-structure-of-joseph-campbell-monomyth.html for reference, it might also help with narrative level building in case plot is suffering. 

I didn't see the sister idea when I first posted this, which is awesome, but maybe at some point there could still be a narrative level where the player 'goes it alone' to reflect. Since PC doesn't talk, maybe this can be presented externally by other V/A cues, like desaturated colors/very dark room, sparse/no music, interactive media i.e. a note found on a skeleton of a previous tower climber that lost their mind/starved, etc.

**Comment by strutcode** [comment]
I like the idea of the silent protagonist. Good interactions are hard to write and the more we leave to the player's imagination the better probably.

In the same vein, I would prefer something more implicit than a sister/person telling you what your goal is and how to solve puzzles. That tends to come off as cheesy/preachy to the player. Let's not forget how well loved Navi was.

I think rooms dedicated to narrative would not be well received. Why not integrate the narrative into the puzzles? Working on separate floors gives us creative freedom but we don't have to work completely in silos. I think we also don't need to be so rigid as to have specific numbers or ratios of rooms.

On the same note I like the idea of boss battles as a change of pace. Maybe those could be an opportunity to lay out some exposition as the player is coming down from a victory high?

**Comment by Xahell** [comment]
@strutcode To narrow down your comment, for this project, are you afraid of poor writing, or are you a gamer who prefers games without explicit narration (or both)?

**Comment by strutcode** [comment]
I guess you could say I’m afraid of bad writing. Not that we’ll have bad writers necessarily but just because of the nature of the project. There will be a lot of clashing ideas and probably not a lot of the kind of lengthy discussion and play testing that leads to really strong narratives.

If we provide a narrative framework that accommodates the type of project it is the end result is likely to be much better for it.

**Comment by Xahell** [comment]
I'll chew on that a bit and make a new proposal in the evening, with a first version of texts and lore included.
